[target.'cfg(target_arch = "riscv32")']
runner    = "probe-rs run --preverify"
rustflags = [
    "--cfg", "embedded_test",

    "-C", "link-arg=-Tembedded-test.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "probe-rs run --preverify"
rustflags = [
    "--cfg", "embedded_test",

    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tembedded-test.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=-Wl,-Tlinkall.x",
]

[env]
DEFMT_LOG = "info,embedded_test=warn"
ESP_HAL_EMBASSY_CONFIG_TIMER_QUEUE="multiple-integrated"

[unstable]
build-std = ["core", "alloc"]

[net]
git-fetch-with-cli = true

# https://doc.rust-lang.org/cargo/reference/profiles.html#test
# Test and bench profiles inherit from dev and release respectively.
[profile.dev]
codegen-units    = 1
debug            = 2
debug-assertions = true
incremental      = false
opt-level        = "z"
overflow-checks  = true

[profile.release]
codegen-units    = 1
debug            = 2
debug-assertions = true
incremental      = false
opt-level        = 3
lto              = false # LTO (thin or fat) miscompiles some tests on RISC-V
overflow-checks  = true
